name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write   # Required for OIDC token exchange
  contents: read    # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # MUST match "Audience" in JFrog OIDC Integration screen
      OIDC_AUDIENCE: 'jfrog-github'
      # MUST match "Provider Name" in JFrog Integration screen (Screenshot 3 shows 'ganesh')
      OIDC_PROVIDER: 'yashwithan' 
      PLATFORM_REPO: 'ganesh-oidc-vir'
    
    defaults:
      run:
        working-directory: ./package

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Setup Node
        uses: actions/setup-node@v4 
        with:
          node-version: '20'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4 
        env:
          JF_URL: ${{ secrets.JF_URL }}
          OIDC_3: ${{ secrets.OIDC_3 }}
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}

      - name: Set CLI Config
        # This command creates the temporary .npmrc required for the build
        run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO

      - name: Install Dependencies
        run: jf npm install

      - name: Run tests
        run: npm test

      - name: Publish
        run: jf npm publish 

      - name: Publish Build info
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
